#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Home\Index\action.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Home\Index\action.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Home\Index\action.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Home/Index/action.cshtml")]
    public partial class _Home_Index_action_cshtml : System.Web.Mvc.WebViewPage<Dal.AccountModel>
    {
        public _Home_Index_action_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Home\Index\action.cshtml"
  
    Layout = "~/Views/Shared/_PublicLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("pagetitle", () => {

WriteLiteral("\r\n    Главная страница чата\r\n");

});

WriteLiteral("\r\n");

DefineSection("stylesheet", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Home\Index\action.cshtml"
Write(Styles.Render("~/Modules/Home/Index/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("headscripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Home\Index\action.cshtml"
Write(Scripts.Render("~/Libraries/Components/Timers/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Home\Index\action.cshtml"
Write(Scripts.Render("~/Libraries/Components/WebApi/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Home\Index\action.cshtml"
Write(Scripts.Render("~/Libraries/Components/WebApi/Common/js"));

            
            #line default
            #line hidden
WriteLiteral("    \r\n");

});

WriteLiteral("\r\n");

DefineSection("bodyscripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Home\Index\action.cshtml"
Write(Scripts.Render("~/Modules/Home/Index/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n<a");

WriteLiteral(" id=\"api-messages-sendmessage\"");

WriteLiteral(" href=\"/api/messages/sendmessage\"");

WriteLiteral(" class=\"hidden\"");

WriteLiteral("></a>\r\n<a");

WriteLiteral(" id=\"api-messages-getmessages\"");

WriteLiteral(" href=\"/api/messages/getmessages\"");

WriteLiteral(" class=\"hidden\"");

WriteLiteral("></a>\r\n\r\n<li");

WriteLiteral(" class=\"self hidden self-hidden\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"avatar\"");

WriteLiteral("><img");

WriteLiteral(" src=\"https://i.imgur.com/DY6gND0.png\"");

WriteLiteral(" draggable=\"false\"");

WriteLiteral(" /></div>\r\n    <div");

WriteLiteral(" class=\"msg\"");

WriteLiteral("></div>\r\n</li>\r\n\r\n<li");

WriteLiteral(" class=\"other hidden other-hidden\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"avatar\"");

WriteLiteral("><img");

WriteLiteral(" src=\"https://i.imgur.com/HYcn9xO.png\"");

WriteLiteral(" draggable=\"false\"");

WriteLiteral(" /></div>\r\n    <div");

WriteLiteral(" class=\"msg\"");

WriteLiteral("></div>\r\n</li>\r\n\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <ol");

WriteLiteral(" class=\"chat\"");

WriteLiteral(">\r\n        </ol>        \r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row send-message\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"div-textarea-message\"");

WriteLiteral(" class=\"col-md-11\"");

WriteLiteral(">\r\n            <textarea");

WriteLiteral(" id=\"textarea-message\"");

WriteLiteral(" rows=\"2\"");

WriteLiteral(" class=\"textarea-size\"");

WriteLiteral(" placeholder=\"Type here!\"");

WriteLiteral("></textarea><div");

WriteLiteral(" class=\"emojis\"");

WriteLiteral("></div>        \r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-1\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" id=\"button-send\"");

WriteLiteral(" class=\"btn btn-primary margin-top-30\"");

WriteLiteral(">Отправить</a>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
