#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Accounts\Login\action.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Accounts\Login\action.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Accounts\Login\action.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Accounts\Login\action.cshtml"
    using Libraries.Core.Backend.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Accounts/Login/action.cshtml")]
    public partial class _Accounts_Login_action_cshtml : System.Web.Mvc.WebViewPage<Modules.Core.Accounts.LoginModel>
    {
        public _Accounts_Login_action_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Accounts\Login\action.cshtml"
  
    Layout = "~/Views/Shared/_PublicLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("pagetitle", () => {

WriteLiteral("\r\n    Вход в систему\r\n");

});

DefineSection("stylesheet", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Accounts\Login\action.cshtml"
Write(Styles.Render("~/Modules/Accounts/Login/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"padding-top: 10vh\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-8\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row no-gutter\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"text-align-center\"");

WriteLiteral(">\r\n                    <h2>Вход в чат</h2>\r\n                </div>\r\n");

            
            #line 25 "..\..\Accounts\Login\action.cshtml"
                
            
            #line default
            #line hidden
            
            #line 25 "..\..\Accounts\Login\action.cshtml"
                 using (Html.BeginForm("Login", "Accounts", new {ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group text-align-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 28 "..\..\Accounts\Login\action.cshtml"
                   Write(Html.ValidationSummary(true, "", new { @class= "text-danger validation-summary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"col-md-offset-3 col-md-6\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"control-label\"");

WriteAttribute("for", Tuple.Create(" for=\"", 1218), Tuple.Create("\"", 1249)
            
            #line 33 "..\..\Accounts\Login\action.cshtml"
, Tuple.Create(Tuple.Create("", 1224), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m=>m.Account)
            
            #line default
            #line hidden
, 1224), false)
);

WriteLiteral(">Логин: </label>                                \r\n                            </d" +
"iv>\r\n                            <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 36 "..\..\Accounts\Login\action.cshtml"
                           Write(Html.TextBoxFor(m => m.Account, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 37 "..\..\Accounts\Login\action.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Account, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"row padding-top-15\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-offset-3 col-md-9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Вход\"");

WriteLiteral(" class=\"btn btn-primary col-md-6\"");

WriteLiteral("/>\r\n                                    </div>\r\n                                <" +
"/div>\r\n                            </div>\r\n                        </div>\r\n     " +
"               </div>\r\n");

            
            #line 50 "..\..\Accounts\Login\action.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
